### PR TITLE
Cache node_modules in CI and run npm install before testing

### PR DESCRIPTION
**Pull request by artur-sak13**
Let's see if this fixes the CI errors.

### CODE REVIEW

**Comment by Andrew-Kulpa** [comment]
I'm pretty sure its because `fs` was mocked and the `existsSync` function literally does not exist. I'm currently testing out this theory by mocking that function

**Comment by artur-sak13** [comment]
Try running the tests locally. It only mocks `readFileSync` and `statSync`. It looked like the error was being thrown at `new Context();`

**Comment by Andrew-Kulpa** [comment]
Well `readFileSync` and `existsSync` are called within the constructor of `Context`. I had to mock `readFileSync` to return `{}` otherwise a JSON parse error occurred. `existsSync` was easy enough to fix by just returning `true`. 

Now Ubuntu and MacOS builds work, but windows is failing due to `rimraf` compatibility issues. Check out this issue (which they closed but its not actually resolved): https://github.com/isaacs/rimraf/issues/72

```
    ENOTEMPTY: directory not empty, rmdir 'C:\Users\RUNNER~1\AppData\Local\Temp\action-release\dist'

      37 | 
      38 |   afterEach(() => {
    > 39 |     rimraf.sync(`${TMP_PATH}`);
         |            ^
      40 |   });
      41 | });
      42 | 

      at rmkidsSync (node_modules/rimraf/rimraf.js:357:27)
      at rmdirSync (node_modules/rimraf/rimraf.js:337:7)
      at rimrafSync (node_modules/rimraf/rimraf.js:307:9)
      at node_modules/rimraf/rimraf.js:344:39
          at Array.forEach (<anonymous>)
      at rmkidsSync (node_modules/rimraf/rimraf.js:344:26)
      at rmdirSync (node_modules/rimraf/rimraf.js:337:7)
      at Function.rimrafSync [as sync] (node_modules/rimraf/rimraf.js:307:9)
      at Object.<anonymous> (__tests__/artifactArchiver.test.ts:39:12)

```

**Comment by Andrew-Kulpa** [comment]
I am currently testing a fix based on https://github.com/ipfs/js-ipfs/pull/2243

**Comment by Andrew-Kulpa** [comment]
It worked!

**Pull request closed without merging**
